Repository opensearch-project/dashboards-search-relevance, pull requests merged in 2022-11, with the labels that each got.

#30 Add an initial integration test
  .cypress/integration/1_query_compare.spec.js
  .cypress/plugins/index.js
  .cypress/support/commands.js
  .cypress/support/constants.js
  .cypress/support/index.js
  .cypress/tsconfig.json
  .cypress/utils/event_constants.js
  .gitignore
  cypress.json
  package.json
  yarn.lock
Labels: backport 2.x, backport 2.4

#35 Moving PULL_REQUEST_TEMPLATE.md to .github dir
  .github/PULL_REQUEST_TEMPLATE.md
Labels: backport 2.x, backport 2.4, backport test-backport

#39 Add windows-latest back to test-and-build workflow
  .github/workflows/test-and-build.yml
Labels: backport 2.x, backport 2.4

#43 Add codeowner
  .github/CODEOWNERS
Labels: enhancement, backport 2.x, backport 2.4

#46 Make srdash compatible with default build script
  package.json
Labels: bug

#55 Change results number to displayed results number
  public/components/query_compare/search_result/result_components/result_panel.tsx
Labels: backport 2.x, backport 2.4

#54 Fix backport delete action; Adding Badges for Build and Link Checker
  .github/.codecov.yml
  .github/draft-release-notes-config.yml
  .github/workflows/delete-backport-branch.yml
  .github/workflows/draft-release-notes-workflow.yml
  .github/workflows/link-checker.yml
  .github/workflows/test-and-build.yml
  MAINTAINERS.md
  README.md
  RELEASING.md
  SECURITY.md
Labels: backport 2.x, backport 2.4

#65 release notes for 2.4.0
  release_notes/opensearch-dashboards-search-relevance.release-notes-2.4.0.0-beta1.md
Labels: backport 2.x, backport 2.4

#73 Update the release notes folder name for consistency with other repos
  release-notes/opensearch-dashboards-search-relevance.release-notes-2.4.0.0.md
Labels: backport 2.x, backport 2.4

#77 Fix default tab spacing
  public/components/query_compare/search_result/search_components/search_configs/search_config.tsx
Labels: bug, backport 2.x, backport 2.4

#91 codecov badge; edited documentation in README
  README.md
  release-notes/opensearch-dashboards-search-relevance.release-notes-2.4.0.0.md
Labels: backport 2.x, backport 2.4
