Repository opensearch-project/dashboards-search-relevance, pull requests merged in 2022-10, with the labels that each got.

#5 Add basic mocks
  .gitignore
  common/index.ts
  opensearch_dashboards.json
  package.json
  public/ace-themes/sql_console.js
  public/application.tsx
  public/components/app.tsx
  public/components/common/header/header.scss
  public/components/common/header/header.tsx
  public/components/common_utils/__tests__/utils.test.ts
  public/components/common_utils/utils.ts
  public/components/query_compare/create_index.tsx
  public/components/query_compare/home.scss
  public/components/query_compare/home.tsx
  public/components/query_compare/search_result/index.tsx
  public/components/query_compare/search_result/result_components/result_grid.scss
  public/components/query_compare/search_result/result_components/result_grid_component.tsx
  public/components/query_compare/search_result/result_components/search_result_table.tsx
  public/components/query_compare/search_result/search_components/search_bar.tsx
  public/components/query_compare/search_result/search_components/search_configs.tsx
  public/contexts/index.tsx
  public/index.scss
  public/index.ts
  public/plugin.ts
  public/types.ts
  public/types/index.ts
  server/index.ts
  server/plugin.ts
  server/routes/dsl_route.ts
  server/routes/index.ts
  server/types.ts
  test/jest.config.js
  test/setup.jest.ts
  test/setupTests.ts
  tsconfig.json
  webpack.config.js
  yarn.lock
Labels: v2.4.0, v3.0.0

#23 changing name to camel case: searchRelevanceDashboards
  package.json
Labels: 2.x, 2.4

#25 fixing badly merged README.md
  README.md
Labels: 2.4, backport 2.x

#26 Search Results UI
  public/components/common/flyout.tsx
  public/components/common/header.tsx
  public/components/common/header/header.scss
  public/components/common/header/header.tsx
  public/components/query_compare/create_index.tsx
  public/components/query_compare/home.scss
  public/components/query_compare/home.tsx
  public/components/query_compare/search_result/index.tsx
  public/components/query_compare/search_result/result_components/result_components.scss
  public/components/query_compare/search_result/result_components/result_components.tsx
  public/components/query_compare/search_result/result_components/result_grid.scss
  public/components/query_compare/search_result/result_components/result_grid.tsx
  public/components/query_compare/search_result/result_components/result_grid_component.tsx
  public/components/query_compare/search_result/result_components/result_panel.tsx
  public/components/query_compare/search_result/result_components/search_result_table.tsx
  public/components/query_compare/search_result/search_components/search_bar.tsx
  public/components/query_compare/search_result/search_components/search_configs.tsx
  public/components/query_compare/search_result/search_components/search_configs/search_config.tsx
  public/components/query_compare/search_result/search_components/search_configs/search_configs.scss
  public/components/query_compare/search_result/search_components/search_configs/search_configs.tsx
  public/contexts/index.tsx
  public/contexts/utils.ts
  public/types/index.ts
  server/routes/dsl_route.ts
Labels: 2.4, backport 2.x
