Repository opensearch-project/dashboards-search-relevance, pull requests merged in 2023-01, with the labels that each got.

#113 Update yarn.lock
  yarn.lock
Labels: 2.x, backport 2.x

#124 [Backport 2.x]Unit Test Coverage Threshold (#101)
  .github/.codecov.yml
  .github/workflows/stats.yml
Labels: backport 2.x

#128 Add config rule in release note for security category
  .github/draft-release-notes-config.yml
Labels: 2.x, backport 2.x, v2.5.0, maintenance

#131 Add 2.4.1 release note
  release-notes/opensearch-dashboards-search-relevance.release-notes-2.4.1.0.md
Labels: backport 2.x, backport 2.4, maintenance, backport 2.5

#135 Add release note for 2.5.0
  release-notes/opensearch-dashboards-search-relevance.release-notes-2.5.0.0.md
Labels: 2.x, backport 2.x, v2.5.0, maintenance, backport 2.5

#139 Increment version from 2.4.1 to 2.4.2
  .github/workflows/test-and-build.yml
  opensearch_dashboards.json
  package.json
Labels: 2.4, maintenance

#141 Add workflow for adding untriaged labels
  .github/workflows/add-untriaged.yml
Labels: enhancement
