Repository opensearch-project/dashboards-search-relevance, pull requests merged in 2023-07, with the labels that each got.

#230 Rolling back to anomaly-detection for OS dependency in workflow
  .github/workflows/remote-integ-tests-workflow.yml
Labels: backport 2.x, backport test-backport

#234 Add release notes for 2.9.0
  release-notes/opensearch-dashboards-search-relevance.release-notes-2.9.0.0.md
Labels: v2.9.0

#236 [BUG] Fixing typo in integ test workflow
  .github/workflows/remote-integ-tests-workflow.yml
  release-notes/opensearch-dashboards-search-relevance.release-notes-2.9.0.0.md
Labels: backport 2.x, CI, backport 2.8
