Repository opensearch-project/dashboards-search-relevance, pull requests merged in 2024-09, with the labels that each got.

#428 New page header for search relevance
  common/index.ts
  public/application.tsx
  public/components/app.tsx
  public/components/query_compare/home.tsx
  public/components/query_compare/search_result/index.tsx
  public/components/query_compare/search_result/search_components/__tests__/__snapshots__/search_bar.test.tsx.snap
  public/components/query_compare/search_result/search_components/__tests__/__snapshots__/search_config.test.tsx.snap
  public/components/query_compare/search_result/search_components/__tests__/__snapshots__/search_configs.test.tsx.snap
  public/components/query_compare/search_result/search_components/search_bar.tsx
  public/components/query_compare/search_result/search_components/search_configs/search_config.tsx
Labels: backport 2.x, v2.17.0

#426 Fix sass division warning
  public/components/query_compare/search_result/result_components/result_grid.scss
Labels: backport 2.x, backport 2.17

#420 Update Links in Documentation
  CONTRIBUTING.md
  DEVELOPER_GUIDE.md
Labels: backport 2.x, backport 2.17

#434 Adding Release Notes for 2.17
  release-notes/opensearch-dashboards-search-relevance.release-notes-2.17.0.0.md
Labels: backport 2.x, backport 2.17

#450 Bumping actions/upload-artifact@v1 to v4
  .github/workflows/test-and-build.yml
Labels: backport 2.x, infra

#449 [Fit&Finish] update query compare card icon
  public/components/service_card/icon.svg
Labels: backport 2.x
